Update python_publish.yml

diff --git a/.github/workflows/python_publish.yml b/.github/workflows/python_publish.yml
--- a/.github/workflows/python_publish.yml
+++ b/.github/workflows/python_publish.yml
@@ -9,10 +9,8 @@
 name: Upload Python Package
 
 on:
-  workflow_run:
-    workflows: [Release]
-    types:
-      - completed
+  release:
+    types: [published]
 
 jobs:
   build_ion_python_wheels:
@@ -26,23 +24,22 @@ jobs:
       - uses: actions/checkout@v4
 
 
-      - name: GitHub Tag Name
-        run: |
-          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
-          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
-          echo ${{ github.event.release.tag_name }}
-          echo $(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)
-
       - uses: robinraju/release-downloader@v1.9
         with:
+          repository: "fixstars/ion-kit"
           latest: false
           fileName: "ion-kit*"
-          tag: ${{ github.event.client_payload.ION_KIT_VERSION }}
+          tag: ${{ github.event.release.tag_name }}
 
 
       - name: Copy macos file
         if: runner.os == 'macOS'
         run: |
+          export ION_KIT_VERSION=${{ github.event.release.tag_name }}
+          if [ ! -f ion-kit-*macos.tar.gz ]; then
+            echo "Error: ion-kit $ION_KIT_VERSION macos package is missing"
+            exit 1 
+          fi
           mkdir $GITHUB_WORKSPACE/macos
           tar xzf  ion-kit-*macos.tar.gz  -C $GITHUB_WORKSPACE/macos --strip-components 1
           cp  $GITHUB_WORKSPACE/macos/lib/libHalide.17.0.1.dylib python/ionpy/module/macos/libHalide.17.dylib
@@ -53,6 +50,11 @@ jobs:
       - name: Copy linux file
         if: runner.os == 'Linux'
         run: |
+          if [ ! -f ion-kit-*linux.tar.gz ]; then
+            echo "Error: ion-kit $ION_KIT_VERSION linux package is missing"
+            exit 1 
+          fi
+          export ION_KIT_VERSION=${{ github.event.release.tag_name }}
           mkdir $GITHUB_WORKSPACE/linux
           tar xzf  ion-kit-*linux.tar.gz  -C $GITHUB_WORKSPACE/linux --strip-components 1
           cp  $GITHUB_WORKSPACE/linux/lib/libion-bb.so python/ionpy/module/linux/libion-bb.so
@@ -64,6 +66,11 @@ jobs:
         if: runner.os == 'Windows'
         run: |
           mkdir windows
+          $ION_KIT_VERSION = "${{ github.event.release.tag_name }}"
+          if (-not (Get-ChildItem -Path . -Filter "ion-kit-*windows.zip" -ErrorAction SilentlyContinue)) {
+            Write-Host "Error: ion-kit $ION_KIT_VERSION windows pakage is missing"
+            exit 1
+          }
           unzip  ion-kit-*windows.zip  && mv ion-kit*/*  windows
           cp  windows/bin/Halide.dll python/ionpy/module/windows/Halide.dll
           cp  windows/bin/ion-core.dll python/ionpy/module/windows/ion-core.dll
@@ -88,7 +95,7 @@ jobs:
           CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""
           CIBW_SKIP: "*-win32 *i686 *musllinux*"
           CIBW_BUILD: cp39-*
-          CIBW_ENVIRONMENT: ION_KIT_VERSION=${{ github.event.client_payload.ION_KIT_VERSION }}
+          CIBW_ENVIRONMENT: ION_KIT_VERSION=${{ github.event.release.tag_name }}
 
 
       - uses: actions/upload-artifact@v4
@@ -115,13 +122,15 @@ jobs:
 
       - uses: robinraju/release-downloader@v1.9
         with:
+          repository: "fixstars/ion-kit"
           latest: true
           fileName: "ion-kit*"
-          tag: ${{ github.event.client_payload.ION_KIT_VERSION }}
+          tag: ${{ github.event.release.tag_name }}
 
       - name: Copy macos file
         if: runner.os == 'macOS'
         run: |
+          export ION_KIT_VERSION=${{ github.event.release.tag_name }}
           mkdir $GITHUB_WORKSPACE/macos
           tar xzf  ion-kit-*macos.tar.gz  -C $GITHUB_WORKSPACE/macos --strip-components 1
           cp  $GITHUB_WORKSPACE/macos/lib/libHalide.17.0.1.dylib python/ionpy/module/macos/libHalide.17.dylib
@@ -136,6 +145,7 @@ jobs:
       - name: Copy linux file
         if: runner.os == 'Linux'
         run: |
+          export ION_KIT_VERSION=${{ github.event.release.tag_name }}
           mkdir $GITHUB_WORKSPACE/linux
           tar xzf  ion-kit-*linux.tar.gz  -C $GITHUB_WORKSPACE/linux --strip-components 1
           cp  $GITHUB_WORKSPACE/linux/lib/libion-bb.so python/ionpy/module/linux/libion-bb.so
@@ -151,6 +161,7 @@ jobs:
         if: runner.os == 'Windows'
         run: |
           mkdir windows
+          set ION_KIT_VERSION=${{ github.event.release.tag_name }}
           unzip  ion-kit-*windows.zip  && mv ion-kit*/*  windows
           cp  windows/bin/Halide.dll python/ionpy/module/windows/Halide.dll
           cp  windows/bin/ion-core.dll python/ionpy/module/windows/ion-core.dll
@@ -184,7 +195,7 @@ jobs:
           CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""
           CIBW_SKIP: "*-win32 *i686 *musllinux*"
           CIBW_BUILD: cp39-*
-          CIBW_ENVIRONMENT: ION_KIT_VERSION=${{ github.event.client_payload.ION_KIT_VERSION }} USE_CONTRIB=TRUE
+          CIBW_ENVIRONMENT: ION_KIT_VERSION=${{ github.event.release.tag_name }} USE_CONTRIB=TRUE
 
       - uses: actions/upload-artifact@v4
         with:
