Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -24,10 +24,13 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Setup dependencies
-        shell: bash
         run: |
           # Halide
-          curl --fail https://github.com/halide/Halide/releases/download/v17.0.1/Halide-1
+          if [ ! -f ion-kit-*linux.tar.gz ]; then
+            echo "Error: ion-kit-*macos.tar.gz is missing"
+            exit 1 
+          fi
+     
   
 
 
