Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,9 +10,11 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Setup dependencies
-        shell: bash
         run: |
-          # Halide
+          if [ ! -f ion-kit-*linux.tar.gz ]; then
+            echo "Error: ion-kit-*macos.tar.gz is missing"
+            exit 1 
+          fi
           curl --fail https://github.com/halide/Halide/releases/download/v17.0.1/Halide-1
   
 
@@ -25,12 +27,12 @@ jobs:
       - uses: actions/checkout@v4
       - name: Setup dependencies
         run: |
-          # Halide
-          if [ ! -f ion-kit-*linux.tar.gz ]; then
-            echo "Error: ion-kit-*macos.tar.gz is missing"
-            exit 1 
-          fi
-     
+            DIR ion-kit-*linux.tar.gz >nul 2>&1
+            IF ERRORLEVEL 1 (
+              ECHO Error: ion-kit-*linux.tar.gz is missing
+              EXIT /B 1
+            )
+
   
 
 
@@ -40,6 +42,13 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+      - name: Setup dependencies
+        run: |
+          if [ ! -f ion-kit-*linux.tar.gz ]; then
+            echo "Error: ion-kit-*macos.tar.gz is missing"
+            exit 1 
+          fi
+
 
 
 
